package plan

import (
	"fmt"
	"time"

	"github.com/anshkanyadi/rift/clock"
	"github.com/anshkanyadi/rift/internal/rng"
)

// GeneratorVersion changes when generation changes shape. It is provenance, not
// behaviour: a plan generated by version 3 executes identically under version 4,
// because execution reads the plan and not the generator.
const GeneratorVersion = 1

// GenConfig is what a seed is turned into a plan against.
type GenConfig struct {
	Nodes        int
	Duration     time.Duration
	TickInterval time.Duration
	MaxOffset    time.Duration
	MaxSteps     uint64

	// Faults bounds how much the generator may do. Zero values mean "none of
	// that kind", so a quiet plan is expressible and a hunt can widen the mix
	// without editing the generator.
	Crashes    int
	Partitions int
	Holds      int
	ClientOps  int
}

// DefaultGenConfig is a small three-node run with every fault kind present.
func DefaultGenConfig() GenConfig {
	return GenConfig{
		Nodes:        3,
		Duration:     30 * time.Second,
		TickInterval: 10 * time.Millisecond,
		MaxOffset:    500 * time.Millisecond,
		MaxSteps:     2_000_000,
		Crashes:      2,
		Partitions:   2,
		Holds:        1,
		ClientOps:    40,
	}
}

// Materialize turns a seed into a plan.
//
// This is the *only* phase that draws sequentially, and it draws freely:
// everything it decides is written into the plan, so nothing here has to be
// re-derivable later. Named sub-streams keep one decision from shifting
// another -- adding a client op cannot reshuffle the network schedule -- which
// is what stops an unrelated change from invalidating the whole corpus.
func Materialize(seed uint64, cfg GenConfig) (*Plan, error) {
	if cfg.Nodes <= 0 {
		return nil, fmt.Errorf("plan: %d nodes", cfg.Nodes)
	}
	root := rng.New(seed)

	p := &Plan{
		SchemaVersion: SchemaVersion,
		Provenance:    Provenance{Seed: seed, GeneratorVersion: GeneratorVersion},
		Config: Config{
			Nodes:          cfg.Nodes,
			DurationNS:     int64(cfg.Duration),
			TickIntervalNS: int64(cfg.TickInterval),
			MaxOffsetNS:    int64(cfg.MaxOffset),
			MaxSteps:       cfg.MaxSteps,
		},
		Keys: Keys{
			Net:        root.DeriveKey("net").String(),
			EngineSync: root.DeriveKey("engine_sync").String(),
			ClockJit:   root.DeriveKey("clock").String(),
			Raft:       root.DeriveKey("raft").String(),
		},
		Clock:  ClockPlan{EpochNS: defaultEpochNS},
		Assert: Assert{MinFires: map[string]uint64{}},
	}

	genNetwork(p, root.Derive("gen.net"), cfg)
	genClocks(p, root.Derive("gen.clock"), cfg)
	genFaults(p, root.Derive("gen.fault"), cfg)
	genWorkload(p, root.Derive("gen.workload"), cfg)

	if err := p.Validate(); err != nil {
		return nil, fmt.Errorf("plan: generator produced an invalid plan: %w", err)
	}
	return p, nil
}

// defaultEpochNS mirrors clock.DefaultEpoch. It is written into every plan
// rather than defaulted at execution, so that a plan's wall readings do not
// change when the constant does.
const defaultEpochNS = 1_600_000_000_000_000_000

func genNetwork(p *Plan, r rng.Rand, cfg GenConfig) {
	for from := range cfg.Nodes {
		for to := range cfg.Nodes {
			if from == to {
				continue
			}
			p.Network.Links = append(p.Network.Links, Link{
				From:         from,
				To:           to,
				DropPerMille: uint64(r.IntN(30)),
				DupPerMille:  uint64(r.IntN(6)),
				LatMinNS:     int64(100+r.IntN(400)) * int64(time.Microsecond),
				LatMaxNS:     int64(1+r.IntN(6)) * int64(time.Millisecond),
				TailPerMille: uint64(r.IntN(10)),
				TailMaxNS:    int64(20+r.IntN(120)) * int64(time.Millisecond),
			})
		}
	}
	p.Assert.MinFires["sent"] = 1
}

func genClocks(p *Plan, r rng.Rand, cfg GenConfig) {
	// Holds are chosen first, because a hold *is* a disciplining of the
	// oscillator: a node under one has its skew authored by the hold, not by
	// free drift. Layering a hold on a drifting base is rejected by the clock
	// package -- the hold's target would depend on when it began -- and the
	// right fix is here rather than a looser rule there.
	held := make([]bool, cfg.Nodes)
	for i := range cfg.Holds {
		if cfg.Nodes < 2 {
			break
		}
		a := r.IntN(cfg.Nodes)
		b := (a + 1 + r.IntN(cfg.Nodes-1)) % cfg.Nodes
		if held[b] {
			continue // one hold per node; two would fight over its timeline
		}
		held[b] = true

		// The realization alternates rather than being drawn, so a generated
		// corpus contains both kinds by construction: they stress different
		// consumers, and a corpus of only one has a blind spot.
		realize := "slew"
		ramp := int64(2 * time.Second)
		if i%2 == 1 {
			realize = "step"
			ramp = 0
		}

		width := int64(time.Second) + int64(r.IntN(int(2*time.Second)))
		from := ramp + int64(r.IntN(int(p.Config.DurationNS/2)))
		p.Clock.Holds = append(p.Clock.Holds, Hold{
			A: a, B: b,
			AtPPB:   clock.Percent(90),
			FromNS:  from,
			ToNS:    from + width,
			RampNS:  ramp,
			Realize: realize,
		})
		p.Assert.MinFires["clock-hold"] = 1
	}

	for n := range cfg.Nodes {
		nc := NodeClock{Node: n}
		if !held[n] {
			// A drift of up to +-200 ppm, which is a realistic crystal.
			ppm := int64(r.IntN(401) - 200)
			nc.Skew = []Segment{{StartNS: 0, OffNS: 0, SlopePPB: ppm * 1000}}
		}
		p.Clock.Nodes = append(p.Clock.Nodes, nc)
	}
}

func genFaults(p *Plan, r rng.Rand, cfg GenConfig) {
	dur := p.Config.DurationNS

	for range cfg.Crashes {
		n := r.IntN(cfg.Nodes)
		at := int64(r.IntN(int(dur)))
		down := int64(r.IntN(int(2 * time.Second)))
		p.Faults.Entries = append(p.Faults.Entries,
			Entry{AtNS: at, Action: "crash", Node: n},
			Entry{AtNS: at + down, Action: "restart", Node: n},
		)
		p.Assert.MinFires["crash"] = 1
		p.Assert.MinFires["restart"] = 1
	}

	for i := range cfg.Partitions {
		if cfg.Nodes < 2 {
			break
		}
		a := r.IntN(cfg.Nodes)
		b := (a + 1 + r.IntN(cfg.Nodes-1)) % cfg.Nodes
		at := int64(r.IntN(int(dur)))
		width := int64(r.IntN(int(3 * time.Second)))

		// Half the partitions are one-way. The asymmetric case is the geometry
		// behind a node that can send but not receive, and symmetric cuts never
		// produce it -- so a generator that only made symmetric partitions
		// would have a permanent blind spot.
		cut, heal := "cut", "heal"
		if i%2 == 0 {
			cut, heal = "cut_both", "heal_both"
		}
		p.Faults.Entries = append(p.Faults.Entries,
			Entry{AtNS: at, Action: cut, From: a, To: b},
			Entry{AtNS: at + width, Action: heal, From: a, To: b},
		)
		p.Assert.MinFires["partition"] = 1
	}

	sortEntries(p.Faults.Entries)
}

func genWorkload(p *Plan, r rng.Rand, cfg GenConfig) {
	dur := p.Config.DurationNS
	for i := range cfg.ClientOps {
		kind := "put"
		if r.IntN(2) == 0 {
			kind = "get"
		}
		p.Workload.Ops = append(p.Workload.Ops, Op{
			AtNS:   int64(r.IntN(int(dur))),
			Client: r.IntN(3),
			Seq:    uint64(i + 1),
			Kind:   kind,
			Key:    fmt.Sprintf("k%02d", r.IntN(8)),
			Value:  fmt.Sprintf("v%d", r.IntN(100)),
		})
	}
	sortOps(p.Workload.Ops)
}

// sortEntries and sortOps put the plan in time order. Insertion sort by
// (instant, index) rather than sort.Slice: it is stable by construction, and a
// plan whose entries reorder between two generations of the same seed would
// diff for no reason.
func sortEntries(es []Entry) {
	for i := 1; i < len(es); i++ {
		for j := i; j > 0 && es[j].AtNS < es[j-1].AtNS; j-- {
			es[j], es[j-1] = es[j-1], es[j]
		}
	}
}

func sortOps(os []Op) {
	for i := 1; i < len(os); i++ {
		for j := i; j > 0 && os[j].AtNS < os[j-1].AtNS; j-- {
			os[j], os[j-1] = os[j-1], os[j]
		}
	}
}
