package differential

import (
	"errors"
	"os"
	"path/filepath"
	"testing"
)

// THE FIXTURES ARE THE SHARED ARTIFACT. These bytes are read by the C++
// classifier too, and were produced by neither decoder — see
// seeds/differential/format/README.md.
//
// A fixture generated by either encoder would test that that decoder agrees
// with that encoder, which is the question the two-decoder pair exists to not
// assume.
func fixtureDir(t *testing.T) string {
	t.Helper()
	// The package sits at engine/differential; the corpus at seeds/.
	dir := filepath.Join("..", "..", "seeds", "differential", "format")
	if _, err := os.Stat(dir); err != nil {
		t.Fatalf("fixture corpus missing at %s: %v", dir, err)
	}
	return dir
}

func read(t *testing.T, name string) []byte {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(fixtureDir(t), name))
	if err != nil {
		t.Fatalf("reading fixture %s: %v", name, err)
	}
	return b
}

// THE VALUES, NOT MERELY THAT THE BYTES PARSE — and the difference is the whole
// point of the pair.
//
// The first version asserted only that Parse returned no error. BM112 swaps two
// provenance fields in both C++ ends, so the bytes still parse perfectly and the
// wrong string lands in the wrong field: a parse-only assertion passes. A
// shared-fixture check that asks "does it parse?" cannot catch a disagreement
// about what the bytes MEAN, which is the only disagreement it exists for.
//
// The expected values come from the document's terms via the corpus generator,
// never read back from either decoder.
func TestLegalMinimalSaysWhatTheDocumentSaysItSays(t *testing.T) {
	a, err := Parse(read(t, "legal-minimal.diff"))
	if err != nil {
		t.Fatal(err)
	}
	if got, want := a.Provenance.EngineCommit, "abc123"; got != want {
		t.Errorf("engine commit = %q, want %q", got, want)
	}
	if got, want := a.Provenance.ModelCommit, "def456"; got != want {
		t.Errorf("model commit = %q, want %q", got, want)
	}
	if got, want := a.Provenance.Regime, "flush"; got != want {
		t.Errorf("regime = %q, want %q", got, want)
	}
	if got, want := a.Provenance.Seed, uint64(7); got != want {
		t.Errorf("seed = %d, want %d", got, want)
	}
	if got, want := a.Provenance.FlushBytes, uint64(4194304); got != want {
		t.Errorf("flush bytes = %d, want %d", got, want)
	}
	if len(a.Submission) != 1 {
		t.Fatalf("submission = %d ops, want 1", len(a.Submission))
	}
	op := a.Submission[0]
	if op.Kind != OpSet || op.Seq != 1 || string(op.Key) != "a" || string(op.Value) != "1" {
		t.Errorf("op = %+v, want Set a=1 at seq 1", op)
	}
	if a.Watermark != 1 {
		t.Errorf("watermark = %d, want 1", a.Watermark)
	}
	if string(a.Recovered["a"]) != "1" {
		t.Errorf("recovered[a] = %q, want %q", a.Recovered["a"], "1")
	}
	if a.Outcome != Agree {
		t.Errorf("outcome = %v, want agree", a.Outcome)
	}
}

func TestOtherLegalFixturesParse(t *testing.T) {
	for _, name := range []string{"legal-every-op.diff", "legal-unjudged.diff"} {
		a, err := Parse(read(t, name))
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		if a.Provenance.Regime != "flush" {
			t.Fatalf("%s: regime = %q", name, a.Provenance.Regime)
		}
		if len(a.Submission) == 0 {
			t.Fatalf("%s: no operations", name)
		}
	}
}

// EVERY REFUSAL, FROM THE SAME BYTES THE C++ CLASSIFIER REFUSES. The two need
// not agree on WHICH error fires when a file breaks more than one rule — only
// that neither accepts it.
func TestRefusedFixturesAreRefused(t *testing.T) {
	cases := map[string]error{
		"refuse-bad-magic.diff":             ErrBadMagic,
		"refuse-truncated.diff":             ErrBadTrailingMagic,
		"refuse-bad-checksum.diff":          nil, // checksum or trailing magic; either is correct
		"refuse-version-2.diff":             ErrUnknownVersion,
		"refuse-unknown-section.diff":       ErrUnknownSection,
		"refuse-duplicate-section.diff":     nil, // duplicate or not-ascending
		"refuse-sections-out-of-order.diff": ErrSectionsNotAscend,
		"refuse-missing-section.diff":       ErrMissingSection,
		"refuse-empty-submission.diff":      ErrEmptySubmission,
		"refuse-recovered-unsorted.diff":    ErrRecoveredNotAscend,
		"refuse-recovered-duplicate.diff":   ErrRecoveredNotAscend,
		"refuse-unknown-outcome.diff":       ErrUnknownOutcome,
		"refuse-no-engine-commit.diff":      ErrMissingCommit,
		"refuse-no-model-commit.diff":       ErrMissingCommit,
		"refuse-dirty-commit.diff":          ErrDirtyCommit,
		"refuse-no-regime.diff":             ErrMissingRegime,
		"refuse-sequences-backwards.diff":   ErrSequencesNotMonotone,
		"refuse-trailing-bytes.diff":        ErrTrailingBytes,
	}
	for name, want := range cases {
		_, err := Parse(read(t, name))
		if err == nil {
			t.Errorf("%s: accepted", name)
			continue
		}
		if want != nil && !errors.Is(err, want) {
			t.Errorf("%s: got %v, want %v", name, err, want)
		}
	}
}

// AN UNJUDGED ARTIFACT PARSES AND FAILS THE CORPUS GATE — the C++ side asserts
// the same pair, from the same bytes.
func TestUnjudgedParsesAndFailsTheGate(t *testing.T) {
	a, err := Parse(read(t, "legal-unjudged.diff"))
	if err != nil {
		t.Fatal(err)
	}
	if a.Outcome != Unrun {
		t.Fatalf("outcome = %v, want unrun", a.Outcome)
	}
	if err := RequireJudged(a); !errors.Is(err, ErrUnjudged) {
		t.Fatalf("gate = %v, want ErrUnjudged", err)
	}
}

// GF-14: THE OTHER HALF. A judged artifact passes, or the gate could be one
// that refuses everything.
func TestJudgedPassesTheGate(t *testing.T) {
	a, err := Parse(read(t, "legal-minimal.diff"))
	if err != nil {
		t.Fatal(err)
	}
	if err := RequireJudged(a); err != nil {
		t.Fatalf("gate refused a judged artifact: %v", err)
	}
}

// THE BOUNDED FLAGS SURVIVE, which is the distinction an empty key cannot
// carry: DeleteRange(At(""), At("")) and DeleteRange(nil, nil) are different
// operations and must not be the same bytes.
func TestAnEmptyBoundIsDistinguishedFromAnUnboundedOne(t *testing.T) {
	a, err := Parse(read(t, "legal-every-op.diff"))
	if err != nil {
		t.Fatal(err)
	}
	var sawUnbounded, sawEmptyBounded bool
	for _, op := range a.Submission {
		if op.Kind != OpDeleteRange {
			continue
		}
		if !op.StartBounded && !op.EndBounded {
			sawUnbounded = true
		}
		if op.StartBounded && op.EndBounded && len(op.Key) == 0 && len(op.Value) == 0 {
			sawEmptyBounded = true
		}
	}
	if !sawUnbounded || !sawEmptyBounded {
		t.Fatalf("the fixture must carry both shapes: unbounded=%v emptyBounded=%v",
			sawUnbounded, sawEmptyBounded)
	}
}
