package differential

import (
	"errors"
	"os"
	"path/filepath"
	"testing"
)

// THE FIXTURES ARE THE SHARED ARTIFACT. These bytes are read by the C++
// classifier too, and were produced by neither decoder — see
// seeds/differential/format/README.md.
//
// A fixture generated by either encoder would test that that decoder agrees
// with that encoder, which is the question the two-decoder pair exists to not
// assume.
func fixtureDir(t *testing.T) string {
	t.Helper()
	// The package sits at engine/differential; the corpus at seeds/.
	dir := filepath.Join("..", "..", "seeds", "differential", "format")
	if _, err := os.Stat(dir); err != nil {
		t.Fatalf("fixture corpus missing at %s: %v", dir, err)
	}
	return dir
}

func read(t *testing.T, name string) []byte {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(fixtureDir(t), name))
	if err != nil {
		t.Fatalf("reading fixture %s: %v", name, err)
	}
	return b
}

func TestLegalFixturesAreAccepted(t *testing.T) {
	for _, name := range []string{"legal-minimal.diff", "legal-every-op.diff", "legal-unjudged.diff"} {
		a, err := Parse(read(t, name))
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		if a.Provenance.Regime == "" {
			t.Fatalf("%s: no regime", name)
		}
		if len(a.Submission) == 0 {
			t.Fatalf("%s: no operations", name)
		}
	}
}

// EVERY REFUSAL, FROM THE SAME BYTES THE C++ CLASSIFIER REFUSES. The two need
// not agree on WHICH error fires when a file breaks more than one rule — only
// that neither accepts it.
func TestRefusedFixturesAreRefused(t *testing.T) {
	cases := map[string]error{
		"refuse-bad-magic.diff":             ErrBadMagic,
		"refuse-truncated.diff":             ErrBadTrailingMagic,
		"refuse-bad-checksum.diff":          nil, // checksum or trailing magic; either is correct
		"refuse-version-2.diff":             ErrUnknownVersion,
		"refuse-unknown-section.diff":       ErrUnknownSection,
		"refuse-duplicate-section.diff":     nil, // duplicate or not-ascending
		"refuse-sections-out-of-order.diff": ErrSectionsNotAscend,
		"refuse-missing-section.diff":       ErrMissingSection,
		"refuse-empty-submission.diff":      ErrEmptySubmission,
		"refuse-recovered-unsorted.diff":    ErrRecoveredNotAscend,
		"refuse-recovered-duplicate.diff":   ErrRecoveredNotAscend,
		"refuse-unknown-outcome.diff":       ErrUnknownOutcome,
		"refuse-no-engine-commit.diff":      ErrMissingCommit,
		"refuse-no-model-commit.diff":       ErrMissingCommit,
		"refuse-dirty-commit.diff":          ErrDirtyCommit,
		"refuse-no-regime.diff":             ErrMissingRegime,
		"refuse-sequences-backwards.diff":   ErrSequencesNotMonotone,
		"refuse-trailing-bytes.diff":        ErrTrailingBytes,
	}
	for name, want := range cases {
		_, err := Parse(read(t, name))
		if err == nil {
			t.Errorf("%s: accepted", name)
			continue
		}
		if want != nil && !errors.Is(err, want) {
			t.Errorf("%s: got %v, want %v", name, err, want)
		}
	}
}

// AN UNJUDGED ARTIFACT PARSES AND FAILS THE CORPUS GATE — the C++ side asserts
// the same pair, from the same bytes.
func TestUnjudgedParsesAndFailsTheGate(t *testing.T) {
	a, err := Parse(read(t, "legal-unjudged.diff"))
	if err != nil {
		t.Fatal(err)
	}
	if a.Outcome != Unrun {
		t.Fatalf("outcome = %v, want unrun", a.Outcome)
	}
	if err := RequireJudged(a); !errors.Is(err, ErrUnjudged) {
		t.Fatalf("gate = %v, want ErrUnjudged", err)
	}
}

// GF-14: THE OTHER HALF. A judged artifact passes, or the gate could be one
// that refuses everything.
func TestJudgedPassesTheGate(t *testing.T) {
	a, err := Parse(read(t, "legal-minimal.diff"))
	if err != nil {
		t.Fatal(err)
	}
	if err := RequireJudged(a); err != nil {
		t.Fatalf("gate refused a judged artifact: %v", err)
	}
}

// THE BOUNDED FLAGS SURVIVE, which is the distinction an empty key cannot
// carry: DeleteRange(At(""), At("")) and DeleteRange(nil, nil) are different
// operations and must not be the same bytes.
func TestAnEmptyBoundIsDistinguishedFromAnUnboundedOne(t *testing.T) {
	a, err := Parse(read(t, "legal-every-op.diff"))
	if err != nil {
		t.Fatal(err)
	}
	var sawUnbounded, sawEmptyBounded bool
	for _, op := range a.Submission {
		if op.Kind != OpDeleteRange {
			continue
		}
		if !op.StartBounded && !op.EndBounded {
			sawUnbounded = true
		}
		if op.StartBounded && op.EndBounded && len(op.Key) == 0 && len(op.Value) == 0 {
			sawEmptyBounded = true
		}
	}
	if !sawUnbounded || !sawEmptyBounded {
		t.Fatalf("the fixture must carry both shapes: unbounded=%v emptyBounded=%v",
			sawUnbounded, sawEmptyBounded)
	}
}
